import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
import {isCorrectAnswer} from '../lib/writing.ts';
import {lessonNotes} from '../lib/lesson-notes.ts';
const course=JSON.parse(fs.readFileSync('lib/course.json','utf8'));
assert(isCorrectAnswer('It’s boiling!', "It's boiling."));
assert(isCorrectAnswer('dude', 'bro / dude / homie / man / dawg'));
assert(!isCorrectAnswer('', 'bro / dude'));
assert(!isCorrectAnswer('It is cold', "It's boiling."));
const fourth=JSON.stringify(lessonNotes[4]);
for(const word of ['and','or','can','your','what','some','one','money','country','luck','bus','subway','plus','run','lunch','above','study','suffer','实词','虚词']) assert(fourth.includes(word),word);
const eleven=JSON.stringify(lessonNotes[11]);
for(const word of ['爆破','摩擦','鼻音','完全爆破','不完全爆破','/tu/','/tə/']) assert(eleven.includes(word),word);
for(const n of course.lessons.map(l=>l.id)) assert(lessonNotes[n]?.length,`notes ${n}`);
assert.equal(course.pages,undefined);
assert(!fs.existsSync('public/course-pages'));
let source=fs.readFileSync('lib/pronunciation.ts','utf8').replace(/import raw from .*?;/,'const raw='+fs.readFileSync('lib/us-pronunciations.json','utf8')+';');
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText;
const {sentenceIPA,wordIPA}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
for(const c of course.cards) assert(!sentenceIPA(c.en).includes('['),c.en);
assert.equal(wordIPA('one'),'wʌn');assert.equal(wordIPA('money'),'ˈmʌni');
console.log('PASS: answer grading, alternatives, weak-form vocabulary, release/to details, 20 lesson notes, no public source pages, pronunciation coverage');
