"use client";
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Trash2} from 'lucide-react';
export function VoiceRecorder({text}:{text:string}){
 const [active,setActive]=useState(false),[url,setUrl]=useState(''),[error,setError]=useState('');const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),blobUrl=useRef(''),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;recorder.current?.state==='recording'&&recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(blobUrl.current)URL.revokeObjectURL(blobUrl.current);};},[]);
 async function record(){if(active){recorder.current?.stop();return;}setError('');try{if(!navigator.mediaDevices||!window.MediaRecorder)throw Error('当前浏览器不支持录音。请使用新版 Chrome、Edge 或 Safari。');const media=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;const r=new MediaRecorder(media),chunks:Blob[]=[];recorder.current=r;r.ondataavailable=e=>chunks.push(e.data);r.onstop=()=>{media.getTracks().forEach(t=>t.stop());if(!alive.current)return;if(blobUrl.current)URL.revokeObjectURL(blobUrl.current);blobUrl.current=URL.createObjectURL(new Blob(chunks,{type:r.mimeType}));setUrl(blobUrl.current);setActive(false);};r.start();setActive(true);}catch(e){setError(e instanceof Error&&e.name==='NotAllowedError'?'麦克风未获允许，请在浏览器中允许后重试。':e instanceof Error?e.message:'录音失败，请重试。');}}
 return <div className="recorder"><p>读一遍，再听听自己。<small>录音仅留在本次页面，不上传。</small></p><div className="button-row"><button onClick={record} className={active?'recording':'secondary'}>{active?<Square size={17}/>:<Mic size={17}/>} {active?'结束录音':'录下这句话'}</button>{url&&<><audio aria-label={'回放：'+text} controls src={url}/><button className="icon-button" aria-label="清除本次录音" onClick={()=>{URL.revokeObjectURL(blobUrl.current);blobUrl.current='';setUrl('');}}><Trash2 size={18}/></button></>}</div>{error&&<p role="alert" className="error">{error}</p>}</div>;
}
