export type Extension = {focus:string;tip:string;trap:string;practice:string;check:string;sourceKeys:string[]};
// Original Chinese explanations and practice prompts, informed by the linked lessons.
export const lessonEnrichment:Record<number,Extension>={
1:{focus:'先分音质，再分长短',tip:'/i/ 的舌位更高、更靠前；/ɪ/ 更放松，嘴稍微打开。不要只把同一个音拉长、缩短。',trap:'seat 和 sit 的区别不是音量大小。先保持相近音量，再听元音的变化。',practice:'交替读 seat—sit、sheep—ship、leave—live，各三遍；再说 I live near the sea.',check:'录音后先听元音是否不同，再检查句末有没有多出“特”或“普”的元音。',sourceKeys:['ee-ih']},
2:{focus:'把 /ɪ/、/ɛ/、/eɪ/ 分开',tip:'从 pin 到 pen，下巴多放下一点；pain 的元音有滑动，pen 的 /ɛ/ 不需要滑向 /ɪ/。',trap:'不要把 bell 读成 bale，也不要把 pen 一律读成 pin。',practice:'按 pin—pen—pain 的顺序读，再打乱顺序；把 pen 放进 I need a pen.',check:'pen 是否保持一个稳定元音？pain 是否有听得到的滑动？',sourceKeys:['ih','eh']},
3:{focus:'开口度与地区差异',tip:'bed 的 /ɛ/ 到 bad 的 /æ/，下巴进一步放低；舌头仍靠前。先练这一对，再读 fast、glass、half。',trap:'cot–caught 合流在美音中很常见。听到 /ɑ/ 与 /ɔ/ 合流时，不要把对方的地区口音当成错误。',practice:'读 bed—bad、bet—bat，再说 That is a bad example. 留意 bad 与 example 中的 /æ/。',check:'先只对比 /ɛ/ 与 /æ/；不要同时追求语速。',sourceKeys:['eh','ae','ah']},
4:{focus:'弱读跟着句子重音走',tip:'schwa /ə/ 出现在非重读位置，短而放松。and、can、some 在不强调时常弱化，但单独说词时通常听到强读。',trap:'/ʌ/ 与 /ə/ 不应只靠“长短”区分；也不能把每个虚词都强行吞掉。',practice:'先读 I can help.，再读 Yes, I CAN.；先读 ham and eggs，再单独强调 AND。',check:'第二种语境中的 can、and 是否更清楚、更突出？单词按钮用于查本音，弱读请对照本课视频。',sourceKeys:['schwa','uh','reduction']},
5:{focus:'卷舌不是把舌尖顶住',tip:'发 /ɝ/ 时舌头向后收拢或隆起，但不要用舌尖抵住上颚。嘴唇可略收圆；/ɚ/ 在非重读音节更短。',trap:'teacher 末尾不要拆成“呃 + 儿”两个音节。herbal 的常见美音不读 h。',practice:'读 bird—teacher、germ—professor；再说 Her teacher is nervous. 找出重读与非重读的卷舌元音。',check:'有没有额外加一个元音？词尾 /ɚ/ 是否比重读 /ɝ/ 更轻？',sourceKeys:['er']},
6:{focus:'圆唇程度不一样',tip:'/u/ 通常更收圆，/ʊ/ 更放松。pool、pull 后面都有 dark L，注意别让词尾 L 掩盖前面的元音。',trap:'full /fʊl/ 与 fool /ful/ 的区别会改变词义。food–foot 同时改变了元音和词尾，不是严格的最小对立词。',practice:'先交替读 pool—pull、fool—full，再读 The pool is full.',check:'先听元音，再听词尾 L；不靠故意拖得特别长来区分。',sourceKeys:['u-uh']},
7:{focus:'双元音要移动',tip:'/oʊ/ 从较圆的起点向更收拢的位置滑动；/aʊ/ 起点更开，随后嘴唇收圆。让动作连续完成。',trap:'不要把 home 读成完全不动的单元音，也不要把 house 拆成两个音节。',practice:'读 go—home、now—house，再说 Go home now. 用慢速观察两种滑动。',check:'每个词仍保持一个音节，嘴型有变化而没有中途停顿。',sourceKeys:['oh','ow']},
8:{focus:'单元音稳定，双元音滑动',tip:'/ɑ/ 的下巴放低，舌头放松；/aɪ/ 从开口位置滑向更高的位置。car 还包含美式 /r/。',trap:'car 和 my 不只是元音不同，不能用这一对单独判断听辨成绩。',practice:'先持续发 /ɑ/，再慢读 /aɪ/；读 father、park、five、time，最后说 My car is outside.',check:'/aɪ/ 有滑动而不是“啊—衣”两个分离音节；park 保留 /r/。',sourceKeys:['ah','ai']},
9:{focus:'同一个字母 t，有不同实现',tip:'top 的 t 清楚，better 中常听到短促闪音 [ɾ]；mountain 中 t 常不明显释放。先听所在环境，再模仿。',trap:'闪音不是每个 t 的默认读法。词典宽式 /t/ 也可能在录音中实现为 [ɾ]。',practice:'依次读 top—water—mountain，再把 water 放进 A bottle of water. 对照视频中的舌尖动作。',check:'有没有把所有 t 都改成 /d/？不要在 mountain 中人为加长停顿。',sourceKeys:['t']},
10:{focus:'双唇闭合，再释放',tip:'/p/、/b/ 都先闭唇。英语重读音节开头的 /p/ 常有较明显气流；/b/ 通常较弱。',trap:'不能用汉语拼音 b、p 直接替换。cap、cab 词尾都不要添加“呃”。',practice:'一手放嘴前，读 pat—bat、pack—back；再读 cap—cab，感受气流与前面元音时长的差别。',check:'词首对比送气，词尾先保持闭唇动作，不用夸张地爆出声音。',sourceKeys:['pb']},
11:{focus:'不释放，也要形成闭塞',tip:'爆破音分为闭塞和释放两个阶段。接另一个辅音时，前一个爆破音可以不明显释放，但舌头或嘴唇仍做出相应动作。',trap:'goodbye 中 /d/ 不明显释放，不等于在所有语境都删除 /d/。不要在 book bag 中间塞进元音。',practice:'慢读 book—bag，再连成 book bag；读 good morning，最后比较单独的 to 与 I need to go 中的 to。',check:'两个词是否直接衔接？to 在不强调时可以用 /tə/，强调时恢复 /tu/。',sourceKeys:['stop','reduction']},
12:{focus:'先听原形的最后一个音',tip:'清音（/t/ 除外）后读 /t/；浊音（/d/ 除外）后读 /d/；/t d/ 后加一个轻的 /ɪd/ 音节。',trap:'不要把 worked、played 都读成两个音节。语流中尾音可弱化，但初学时先掌握完整形式。',practice:'把 worked、played、wanted、needed 按 /t d ɪd/ 分组；再读 I worked. / I worked all day.',check:'worked、played 各一个音节；wanted、needed 各两个。比较词尾与后接元音时的衔接。',sourceKeys:['ed']},
13:{focus:'复数词尾也要按声音判断',tip:'/s z ʃ ʒ tʃ dʒ/ 后需要 /ɪz/；其余清音后 /s/，其余浊音及元音后 /z/。',trap:'字母 e 不代表一定增加音节。likes 是一个音节，boxes 是两个。',practice:'按 cups—dogs—boxes 读三组，再说 Two dogs watch three boxes. 用手轻触喉部比较 /s z/。',check:'/z/ 有声带振动；/ɪz/ 中额外的音节短而轻。',sourceKeys:['sz','ts']},
14:{focus:'让摩擦持续一小会儿',tip:'/ʃ/ 与 /ʒ/ 的口型相似，嘴唇略向前，气流持续；/ʒ/ 增加声带振动。',trap:'treasure 中的 /ʒ/ 不要读成先闭塞再释放的 /dʒ/。leisure 常见美音以 /li/ 开头。',practice:'读 pressure—treasure，再读 vision、measure；把 /ʒ/ 稍延长，体会它可以持续。',check:'是否不小心在 /ʒ/ 前加了 /d/？两种摩擦音的气流都能持续。',sourceKeys:['shzh']},
15:{focus:'破擦音先挡住，再摩擦',tip:'/tʃ dʒ/ 都先形成短暂闭塞，再释放为摩擦；/dʒ/ 是浊音。它们各算一个辅音音素。',trap:'cheap 的开头不是单纯 /ʃ/；jeep 也不是只发 /ʒ/。',practice:'对比 cheap—jeep、chin—gin，再读 Would you like tea? 对照视频听 /d/ 与 /j/ 的结合。',check:'先确认单词首音，再练自然同化，不必为了快而吞掉所有边界。',sourceKeys:['chj']},
16:{focus:'下唇与上齿轻接触',tip:'/f v/ 都让上门齿轻触下唇；/v/ 有声带振动。发 /w/ 时嘴唇收圆，牙齿不需要触唇。',trap:'不要咬紧嘴唇，也不要把 vine 读成 wine。',practice:'交替读 fan—van、fine—vine、feel—veal；再读 Five very fine flowers.',check:'镜子里能看到轻微唇齿接触，/v/ 的振动明显但不必用力挤喉咙。',sourceKeys:['fv']},
17:{focus:'轻触，不是真的咬住舌头',tip:'舌尖略到齿间，保持放松并让气流通过。/θ/ 只有气流，/ð/ 加上声带振动。',trap:'breath /brɛθ/ 是名词，breathe /brið/ 是动词；元音和词尾都不同。',practice:'读 thin、three，再读 this、brother；最后交替读 breath—breathe，比较元音和清浊。',check:'没有把 /θ/ 换成 /s/ 或 /t/；舌尖不伸得过远，气流不中断。',sourceKeys:['th']},
18:{focus:'换阻挡位置，保持鼻腔共鸣',tip:'/m/ 闭嘴唇，/n/ 舌尖接触齿龈，/ŋ/ 舌后部抬起；气流都可以经过鼻腔。',trap:'sing 的末尾通常只有 /ŋ/，不要额外加出 /ɡ/ 或“呃”。',practice:'用同一个元音读 sum—sun—sung，再读 sin—sing；最后说 The sun is warm.',check:'/ŋ/ 时舌尖不需要顶住上齿龈；词尾没有多余的爆破音。',sourceKeys:['m','nng']},
19:{focus:'辅音组合之间不插元音',tip:'/ts dz/ 从短暂闭塞直接进入摩擦；/tr dr/ 在美音中常带破擦色彩，但仍要连到 /r/。',trap:'cats、beds 末尾不要变成“特斯”“德兹”两个独立音节。debts 的 b 不发音。',practice:'读 cats—beds、trust—dream；再读 Two cats sleep on the beds. 尾音轻而完整。',check:'cats、beds 都只有一个音节；不要把 tree 的 /r/ 完全丢掉。',sourceKeys:['trdr','ts','sz']},
20:{focus:'区分 L、W 与弱化的 H',tip:'/l/ 用舌头形成边音，词尾 dark L 还涉及舌后部；/w/ 主要表现为双唇收圆。弱读代词的 /h/ 有时省略。',trap:'单独的 him、her 通常有 /h/，句子中不强调时可能没有；不能把所有 h 都删掉。',practice:'读 light—white、low—well；比较单独的 him 与 Tell him.，再说 I can help HER. 保留强调的 h。',check:'light 的开头有没有误用 /w/？弱读代词与强调代词是否听起来不同？',sourceKeys:['l','h']},
};
